parallel/parallel_src/lib/data_structure/parallel_graph_access.h
PEID is a typealias for int, thus it overflows if the graph has more than 2^31 nodes. This PR replaces the return type with NodeID.
=> getGlobalID() should return NodeID instead of PEID

lib/io/graph_io.cpp, parallel/parallel_src/lib/io/parallel_graph_io.cpp
The current method for saving graphs in METIS format use one `std::endl` after each node. However, `std::endl` is not just a constant for the new line character but also flushes the stream (see http://en.cppreference.com/w/cpp/io/manip/endl). This lowers the writing speed significantly, in particular for graphs with many nodes of low degree. 
This PR replaces the `std::endl` with just a `\n` character. For 3-regular graphs, this improves the writing speed by a factor of about 9.
=> Graph IO speedup

CMakeLists.txt, parallel/modified_kahip/CMakeLists.txt, parallel/parallel_src/CMakeLists.txt
CMake 3.12 is unavailable on some compute servers but CMake 3.10 seems to work too. I tested it on my PC and one of the compute servers.
=> Lower required CMake version and add CMake support for ParHIP

CMakeLists.txt, parallel/modified_kahip/CMakeLists.txt, parallel/parallel_src/CMakeLists.txt
Builds KaHIP and ParHIP interfaces as static and shared libraries. 
**Note:** I've changed the other libraries that are not part of the deployment to `OBJECT` libraries (in CMake), so that they are no longer built as separate static libraries (that should be the same behaviour as the scons scripts, I think). Is this ok or are there use cases for these sub-libraries (i.e. libkaffpa, libmapping, libkaffpa_parallel, libspac, ...)? I changed it because CMake would otherwise refuse to copy them into the interface libraries, although there also seem to be other solutions if those sub-libraries are needed.
=> Add KaHIP and ParHIP interface to CMake build script

SConstruct, interface/SConstruct, misc/example_library_call/SConstruct, parallel/modified_kahip/SConstruct, parallel/modified_kahip/interface/SConstruct, parallel/parallel_src/SConstruct, parallel/parallel_src/interface/SConstruct
-  These simple modifications allow the use of the `compile.sh` script in systems that have only python3
=> Use python3 prin formart in Scons

compile_withcmake.sh
`libkahip` from the `parallel/modified/deploy` has also to be linked if one intends to use the parhip interface. However, using `compile_withcmake.sh` the lib file is not located in the usual deploy folder.
Proposal:
Add the modified kahip lib to deploy/parallel.
=> Add modified kahip lib to deploy/parallel

app/parse_spac_parameters.h
The old regex for the `-social` preconfigurations doesn't work in `edge_partitioning`, this PR fixes that
=> Fix edge_partitioning preconfiguration regex

parallel/modified_kahip/lib/partition/uncoarsening/refinement/kway_graph_refinement/kway_graph_refinement_commons.cpp
Trivial changes to build KaHIP  without OpenMP.
We have an open PR in FEniCS/dolfinx, for using KaHIP as the mesh partitioner
([#451](https://github.com/FEniCS/dolfinx/pull/451)). However OpenMP is a large dependecy that we are currently avoiding. 
This PR would allow the use of KaHIP in FEniCS, and get the mentioned PR merged.
=> Make OpenMP an optional dependency

README.md
The link to the Open MPI project was broken. It now points to the correct website.
=> Fix Open MPI url

CMakeLists.txt
Adds CMake flag `-DUSE_TCMALLOC=On`. If present, search for tcmalloc and link against it if it is available on the system. 
On my system, tcmalloc improves the running time of kaffpa by roughly 5 -- 7%.
=> Add cmake option to link against tcmalloc.

INSTALL, parallel/parallel_src/CMakeLists.txt
I'll note that it would be convenient to be able to build/install just `libparhip_interface.so`, but this isn't supported. Also, if one uses `cmake -DBUILD_SHARED_LIBS=on`, then `libparhip_interface.so` is incomplete (missing symbols like `kaffpaE`). I'd love if this could be supported, but don't understand the rationale behind the present design.
I assume you'll want other public headers installed, but don't know exactly what those are and this is all I need for PETSc.
=> Install ParHIP header

compile_withcmake.sh
Copy `libinterface.dylib` instead of `libinterface.so` on macOS ( part of #82 )
=> Copy *.dylib file on macOS

CMakeLists.txt, compile_withcmake.sh, misc/pymodule/kahip.cpp
I think that this is a more robust and idiomatic approach at building the Python interface. In particular, it also works on macOS.
=> Use pybind11_add_module() to build Python interface

CMakeLists.txt, app/kaffpaE.cpp, app/parse_parameters.h, lib/partition/uncoarsening/refinement/kway_graph_refinement/kway_graph_refinement_commons.cpp, parallel/modified_kahip/app/parse_parameters.h
Hello,
In this pull-request the support for apple clang on mac os is addressed.
**Current Behaviour**
Currently compilation on MacOS fails due to missing include guards around `#include <omp.h>`.
**Changes**
I added these guards in order to make non openmp targets compile on mac os. I added one include in `kaffpaE.cpp` as it is required to have omp support. Furthermore, I adapted the `CMakeLists.txt` to find metis headers on Mac.
Best,
Henrik
=> Add missing USE_OPENMP and apple clang support

compile_withcmake.sh
Addresses #107:
- Remove `cmake -B` to allow CMake versions lower than 3.13 
- Only detect and use number of available cores if `NCORES` is not set as an environment variable
=> Lower CMake version and limit parallelism in compile script

lib/partition/coarsening/matching/gpa/compare_rating.h, parallel/modified_kahip/lib/partition/coarsening/matching/gpa/compare_rating.h
`std::binary_function` is deprecated since C++11 and got removed in C++17. Recent GCC versions output a warning about it.
Since we're not using any of the types defined by `std::binary_function` it seems as if we could just remove it.
=> Remove use of deprecated std::binary_function

parallel/parallel_src/interface/parhip_interface.cpp
Add the same summary output as in the binary, otherwise it's not possible to measure the partitioning time of ParHIP without the overhead of constructing the initial graph data structure
=> Add summary output to the library interface

lib/data_structure/graph_access.h
In the following functions, if graphref is valid, then it re-allocates without being deleted first. The fix is just to delete it if it is not NULL before any allocation.
=> delete graphref before re-allocating it

README.md, interface/kaHIP_interface.cpp
Description: 
- The process_mapping function in the KaHIP Interface returned partition IDs for all nodes before the mapping algorithm recomputed the partition indices. This has now been fixed.
- Additionally, partition_config.k was not computed in the process_mapping function in the KaHIP Interface, and was simply set to 1. Now, the value of partition_config.k is computed as a multiple of group sizes of partitions in the heirarchy (as required). This fixes another bug pertaining to the vector 'perm_rank' used by the mapping algorithms which is initialized to the size of partition_config.k. After this fix, calls to mapping algorithms from the KaHIP Interface work correctly, and so does the computation of the total_qap score. 
NOTE: These bugs only exist in the KaHIP Interface, and not in …
=> [KaHIP Interface - Process Mapping] bug fix + partition update after mapping 

CMakeLists.txt, app/edge_evaluator.cpp, parallel/parallel_src/app/dspac.cpp, parallel/parallel_src/lib/dspac/dspac.cpp, parallel/parallel_src/lib/dspac/dspac.h, parallel/parallel_src/lib/dspac/edge_balanced_graph_io.cpp, parallel/parallel_src/lib/dspac/edge_balanced_graph_io.h
dSPAC sorts the neighborhoods of vertices during IO, but does not revert to the original edge order when outputting the edge partition. This PR fixes that (and also adds a tool to evaluate the partition file).
=> Distributed SPAC: fix edge partition order

interface/kaHIP_interface.cpp, interface/kaHIP_interface.h, lib/spac/spac.cpp, lib/spac/spac.h
Currently, the edge partitioning code ignores vertex and edge weights. This PR adds rudimentary support, **but**: for weighted input graphs, it might be harder to find "good" values for the "infinity" edge weight of dominant edges, i.e., one that is respected by the vertex partitioner and does not cause overflows. Contracting the dominant edges as in @adilchhabra 's code would be a much better option; maybe we should integrate his code instead? Would that be a lot of work or just plug'n'play? What do you think Adil?
=> Support weights in edge partitioning
